# Generated by Django 4.1.1 on 2022-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título da receita')),
                ('datatime', models.DateTimeField(auto_now=True)),
                ('mododepreparo', models.TextField(default=True, verbose_name='Modo de preparo')),
                ('ingrediente', models.TextField(default=True)),
            ],
        ),
    ]
